sudo: false
language: go
go:
  - 1.11.x
  - 1.12.x
script: make check_generated test

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - echo "travis go version='$TRAVIS_GO_VERSION'"

# needed for the docker pipe
services:
- docker

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    # it's important to build on the newest version of go:
    condition: $TRAVIS_GO_VERSION =~ ^1\.12
